appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: PvdaHqleZRu1sAKKTOVc50zBHVga8Hou+w/9NtXzkErvHi1lrXiFotu19107ANxaPpnwFOT8zhPKuqV5kjDRtBHyhXkVG8/tDkDvKRjM3+c+pja1IXo188lJxJdnLcF7/D3i0I7nDFWK4ZpM/rYJ04iqrUUdZd6bkcmoRfrCHIXaanRZDUQ+BIbBzqUfMlCYMbto4EM5uIr0jXeN2aPBAGk9RTs30RFt7jOE2CysyxyeaThx0zp77Zg2cNotNH3+ZZZs8utjwt4LVCcXQdcrutjFNIInXuweaPqsQ9YgqR8fEeq9bKCRdU/lsZF0mx6iX0nlMYrvHI6iaeAiiOHfmEAN1VRO2IkTN0f6u0uWa56J2E347gwicHo1R2u8ouEtKO9Tsd/JvXNizztP+uH/8l6jSGY53XVhlPhxkq/HnPIHHio6WK37MnIAFPWzm83SRlOHR6zCcKfTXlOVJz3uI1Y+LKd1BBMxFBtVSmAz5rtx67JOA2j5P70/tMYQeqIaOfGD5Q/rUYEqY0wzlXYH1a9bscFMGbp1kW5Pyy2SNEWuSH7bgk6wPsKsa3c0dTMgbXf+SzStdoGcv1r3ObYw2l+TrI7nWSWfRLUY68KvJ52NC3R8tMLPfHInXrsl9NtYHG9XogFdQYUXC7+zRPVafH76wWYLcxei3RQNiLZszew=}
bot:
  automerge: true
